Repository healthhackersER/CAMA-CORE-Example, pull requests merged in 2020-02, with the labels that each got.

#32 Feature/#31 fix build error
  Screens/FormMetaInfo/MetaInfo.input.component.tsx
Labels: bug

#30 WebView - Feature/module manager
  App.tsx
  Component/Dashboard.component.tsx
  Component/MetaInfo.input.component.tsx
  Component/Module.component.tsx
  Models/Module.ts
  Screens/Camera.screen.tsx
  Screens/Database.screen.tsx
  Screens/Home.screen.tsx
  Screens/Module.screen.tsx
  package.json
Labels: good first issue

#35 Update README.md
  README.md
Labels: documentation

#37 Update README.md
  README.md
Labels: documentation
